CREATE DATABASE BOOKDB;

GRANT ALL privileges ON BOOKDB.* TO 'ohgiraffers'@'%';

show grants for 'ohgiraffers'@'%';

use bookdb;


DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS SEARCH;
DROP TABLE IF EXISTS BOX;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS OUT_MEMBER;

CREATE TABLE IF NOT EXISTS MEMBERS
(
USER_CODE INT,
USER_ID VARCHAR(255) NOT NULL,
USER_PW VARCHAR(255) NOT NULL,
USER_NAME VARCHAR(255) NOT NULL,
USER_PHONE VARCHAR(255),
USER_EMAIL VARCHAR(255),
USER_TYPE INTEGER NOT NULL,
PRIMARY KEY(USER_CODE),
UNIQUE(USER_PHONE),
CHECK(USER_TYPE IN (1, 2, 3))
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BOOKS
(
BOOK_CODE INT,
BOOK_NAME VARCHAR(255) NOT NULL,
BOOK_AUTHOR VARCHAR(255) NOT NULL,
BOOK_GENRE VARCHAR(255) NOT NULL,
BOOK_TYPE VARCHAR(255) NOT NULL,
BOOK_PUBLISHER VARCHAR(255) NOT NULL,
PRIMARY KEY(BOOK_CODE)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS SEARCH
(
SEARCH_ELEMENT VARCHAR(255) NOT NULL,
SEARCH_NAME VARCHAR(255) NOT NULL,
SEARCH_DATE DATE NOT NULL,
USER_CODE INT NOT NULL,
BOOK_CODE INT NOT NULL,
FOREIGN KEY (USER_CODE) REFERENCES MEMBERS (USER_CODE),
FOREIGN KEY (BOOK_CODE) REFERENCES BOOKS (BOOK_CODE)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS BOX
(
RENTAL BOOLEAN NOT NULL,
RENTAL_DATE DATE,
END_DATE DATE,
BUY_DATE DATE,
BOOK_CODE INT NOT NULL,
USER_CODE INT NOT NULL,
FOREIGN KEY(BOOK_CODE) REFERENCES BOOKS (BOOK_CODE),
FOREIGN KEY(USER_CODE) REFERENCES MEMBERS (USER_CODE)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS REQUEST
(
REQUEST_TITLE VARCHAR(255),
REQUEST_AUTHOR VARCHAR(255),
REQUEST_PUBLISHER VARCHAR(255),
USER_CODE INT NOT NULL,
REQUEST_DATE DATE NOT NULL,
FOREIGN KEY(USER_CODE) REFERENCES MEMBERS (USER_CODE)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS OUT_MEMBER
(
OUT_DATE DATE NOT NULL,
USER_CODE INT NOT NULL,
FOREIGN KEY(USER_CODE) REFERENCES MEMBERS (USER_CODE)
)ENGINE=INNODB;
